# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field


class UpdateDeviceRequest(BaseModel):
    n_qubits: int | None = None


class UpdateDeviceResponse(BaseModel):
    message: Annotated[str, Field(examples=["Device is successfully updated."])] = (
        "Device is successfully updated."
    )


class Status(str, Enum):
    available = "available"
    unavailable = "unavailable"


class DeviceStatusUpdate(BaseModel):
    status: Status


class DeviceDataUpdateResponse(BaseModel):
    message: Annotated[str, Field(examples=["Device data updated"])] = (
        "Device data updated"
    )


class DeviceInfoUpdate(BaseModel):
    upload_id: Annotated[str, Field(examples=["4a955d4fb28b4b699cdb8ad2274d3738"])]
    """
    Upload identifier returned by the device_info upload URL endpoint.
    """
    calibrated_at: Annotated[AwareDatetime, Field(examples=["2023-09-10T14:00:00Z"])]
    """
    Calibration timestamp for the uploaded device_info.
    """


class DeviceInfoUploadPresignedURL(BaseModel):
    """
    Presigned URL for uploading device_info.zip to OQTOPUS cloud.
    """

    url: Annotated[str, Field(examples=["https://oqtopus-cloud.s3.amazonaws.com/"])]
    fields: dict[str, Any]


class DeviceInfoUploadResponse(BaseModel):
    upload_id: str
    """
    Upload identifier for confirming the specific device_info upload.
    """
    presigned_url: DeviceInfoUploadPresignedURL
