# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-10-14T08:14:38+00:00
#   version:   0.25.9

from __future__ import annotations

from pydantic import BaseModel


class BadRequest(BaseModel):
    detail: str


class NotFoundError(BaseModel):
    detail: str


class InternalServerError(BaseModel):
    detail: str
