# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-08-28T07:05:25+00:00
#   version:   0.25.8

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class HelloWorldResponse(BaseModel):
    """
    サーバーの状態のレスポンス
    """

    message: str


class Name(RootModel[str]):
    root: Annotated[str, Field(examples=["Mike"])]
