# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-10-09T06:40:46+00:00
#   version:   0.25.9

from __future__ import annotations

from typing import Annotated, Any, Literal, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class InternalJobStatus(
    RootModel[
        Literal["submitted", "ready", "running", "success", "failed", "cancelled"]
    ]
):
    root: Annotated[
        Literal["submitted", "ready", "running", "success", "failed", "cancelled"],
        Field(examples=["submitted"]),
    ]


class JobId(RootModel[UUID]):
    root: Annotated[UUID, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]


class SamplingAction(BaseModel):
    name: Annotated[str, Field(examples=["sampling"], pattern="sampling")]
    nShots: Annotated[int, Field(examples=["1000"], ge=1, le=10000000)]


class SingleOperator(RootModel[list[float]]):
    root: Annotated[
        list[float], Field(examples=[[1.5, 2.8]], max_length=2, min_length=2)
    ]
    """
    Real and imaginary components of complex coef value
    """


class SingleOperatorModel(RootModel[list[Union[str, SingleOperator]]]):
    root: Annotated[list[Union[str, SingleOperator]], Field(max_length=2, min_length=2)]


class Operator(RootModel[list[SingleOperatorModel]]):
    root: Annotated[
        list[SingleOperatorModel],
        Field(examples=[[["X 0 X 1", [1.5, 2.8]], ["Y 0 Z 1", [1.2, -2e-08]]]]),
    ]


class EstimationAction(BaseModel):
    name: Annotated[str, Field(examples=["estimation"], pattern="estimation")]
    method: Annotated[Literal["state_vector", "sampling"], Field(examples=["sampling"])]
    """
    state_vector method valid only for 'simulator' devices
    """
    nShots: Annotated[Optional[int], Field(None, examples=["1000"], ge=1, le=10000000)]
    """
    Parameter valid only for sampling method
    """
    operator: Operator


class Action(RootModel[Union[SamplingAction, EstimationAction]]):
    root: Union[SamplingAction, EstimationAction]


class JobInfo(BaseModel):
    jobId: JobId
    code: Annotated[
        str,
        Field(
            examples=[
                "OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;"
            ]
        ),
    ]
    device: Annotated[str, Field(examples=["Kawasaki"])]
    nQubits: Annotated[Optional[int], Field(None, examples=[None])]
    nNodes: Annotated[Optional[int], Field(None, examples=[12])]
    """
    Parameter valid only for 'simulator' devices
    """
    action: Action
    qubitAllocation: Annotated[
        Optional[dict[str, int]], Field(None, examples=[{"0": 12, "1": 16}])
    ]
    """
    Parameter valid only for QPU devices
    """
    skipTranspilation: Annotated[bool, Field(examples=[False])]
    seedTranspilation: Annotated[Optional[int], Field(None, examples=[873])]
    """
    Parameter valid only if skipTranspilation is false
    """
    seedSimulation: Annotated[Optional[int], Field(None, examples=[39058567])]
    """
    Parameter valid only for 'simulator' devices
    """
    roErrorMitigation: Annotated[
        Optional[Literal["none", "pseudo_inverse", "least_square"]],
        Field(None, examples=["pseudo_inverse"]),
    ]
    """
    Parameter valid only for QPU devices
    """
    nPerNode: Annotated[Optional[int], Field(None, examples=[5], ge=1)]
    """
    Parameter valid only for simulator devices
    """
    simulationOpt: Annotated[
        Optional[dict[str, Any]],
        Field(
            None,
            examples=[
                {
                    "optimizationMethod": "light",
                    "optimizationBlockSize": 1,
                    "optimizationSwapLevel": 1,
                }
            ],
        ),
    ]
    """
    Parameter valid only for simulator devices
    """
    status: InternalJobStatus
    createdAt: Annotated[AwareDatetime, Field(examples=["2022-10-19T11:45:34+09:00"])]


class JobStatusUpdate(BaseModel):
    status: Annotated[Literal["RUNNING"], Field(examples=["RUNNING"])]


class JobStatusUpdateResponse(BaseModel):
    message: str


class InternalFetchableJobStatus(RootModel[Literal["QUEUED", "CANCELLING"]]):
    root: Annotated[Literal["QUEUED", "CANCELLING"], Field(examples=["QUEUED"])]


class UnfetchedJobsResponse(RootModel[list[Union[JobInfo, JobId]]]):
    root: list[Union[JobInfo, JobId]]
