# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class JobStatus(str, Enum):
    submitted = "submitted"
    ready = "ready"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class JobType(str, Enum):
    sampling = "sampling"
    estimation = "estimation"
    multi_manual = "multi_manual"
    sse = "sse"


class OperatorItem(BaseModel):
    pauli: Annotated[str, Field(examples=["X 0 X 1"])]
    """
    The Pauli string.
    """
    coeff: Annotated[list[float] | None, Field(max_length=2, min_length=1)] = None
    """
    Complex coefficient number in the Pauli string representation.
    """


class SamplingResult(BaseModel):
    """
    *(Only for sampling jobs)* JSON string representing the sampling result
    """

    counts: Annotated[
        dict[str, Any],
        Field(examples=['{\n  "10": 84,\n  "11": 387,\n  "10": 454,\n  "01": 75\n}']),
    ]
    divided_counts: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                '{\n  "0": {\n    "10": 84,\n    "11": 387,\n    "10": 454,\n    "01": 75\n  },\n  "1": {\n    "10": 84,\n    "11": 387,\n    "10": 454,\n    "01": 75\n  }'
            ]
        ),
    ] = None


class EstimationResult(BaseModel):
    """
    *(Only for estimation jobs)* The estimated expectation value and the standard deviation
    of the operators specified in `job_info.operator` field which is intended to be provided for estimation jobs.

    """

    exp_value: Annotated[list[float], Field(max_length=2, min_length=1)]
    """
    This field must contain an array of numbers with a maximum length of 2, representing a complex number.
    The first element corresponds to the real part, and the second corresponds to the imaginary part.

    """
    stds: float
    """
    (Only for estimation jobs) The standard deviation value
    """


class JobResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    sampling: SamplingResult | None = None
    estimation: EstimationResult | None = None


class TranspileResult(BaseModel):
    transpiled_program: Annotated[
        str | None,
        Field(
            examples=[
                'OPENQASM 3; include "stdgates.inc"; qubit[2] _all_qubits; let q = _all_qubits[0:1]; h q[0]; cx q[0], q[1];'
            ]
        ),
    ] = None
    stats: Annotated[str | None, Field(...)] = None
    virtual_physical_mapping: Annotated[str | None, Field(...)] = None


class JobInfo(BaseModel):
    program: Annotated[
        list[str],
        Field(
            examples=[
                '[ "OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;" ]'
            ]
        ),
    ]
    """
    A list of OPENQASM3 program. For non-multiprogramming jobs, this field is assumed to contain exactly one program. Otherwise, those programs are combined according to the multiprogramming machinery.
    """
    combined_program: str | None = None
    """
    For multiprogramming jobs, this field contains the combined circuit.
    """
    operator: list[OperatorItem] | None = None
    """
    *(Only for estimation jobs)* The operator (or observable) for which the expectation
    value is to be estimated.

    """
    result: JobResult | None = None
    transpile_result: TranspileResult | None = None
    message: str | None = None
    """
    Describing the reason why there is no result
    """


class JobDef(BaseModel):
    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    name: Annotated[str | None, Field(examples=["Bell State Sampling"])] = None
    description: Annotated[
        str | None, Field(examples=["Bell State Sampling Example"])
    ] = None
    device_id: Annotated[str, Field(examples=["Kawasaki"])]
    shots: Annotated[int, Field(examples=["1000"], ge=1, le=10000000)]
    job_type: JobType
    job_info: JobInfo
    transpiler_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "qubit_allocation": {"0": 12, "1": 16},
                    "skip_transpilation": False,
                    "seed_transpilation": 873,
                }
            ]
        ),
    ] = None
    simulator_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "n_qubits": 5,
                    "n_nodes": 12,
                    "n_per_node": 2,
                    "seed_simulation": 39058567,
                    "simulation_opt": {
                        "optimization_method": "light",
                        "optimization_block_size": 1,
                        "optimization_swap_level": 1,
                    },
                }
            ]
        ),
    ] = None
    mitigation_info: Annotated[
        dict[str, Any] | None,
        Field(examples=[{'ro_error_mitigation"': "pseudo_inverse"}]),
    ] = None
    status: JobStatus
    execution_time: Annotated[float | None, Field(examples=["10.123"])] = None
    submitted_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    ready_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    running_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    ended_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None


class JobStatusUpdate(BaseModel):
    status: Annotated[Literal["running"], Field(examples=["running"])]


class JobStatusUpdateResponse(BaseModel):
    message: str


class UpdateJobInfo(BaseModel):
    combined_program: str | None = None
    transpile_result: TranspileResult | None = None
    result: JobResult | None = None
    message: str | None = None


class UpdateJobInfoRequest(BaseModel):
    overwrite_status: JobStatus | None = None
    """
    Overwrite the job status. If this field is not specified, the status will be updated automatically.
    """
    execution_time: float | None = None
    """
    Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.
    """
    job_info: UpdateJobInfo | None = None


class UpdateJobInfoResponse(BaseModel):
    message: str


class UploadSselogRequest(BaseModel):
    file: bytes


class UploadSselogResponse(BaseModel):
    message: str
