openapi: 3.0.1
info:
  title: OQTOPUS Cloud Admin API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud Admin API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server url
paths:
  /users:
    get:
      tags:
        - user
      summary: get users
      description: get users
      operationId: getUsers
      security:
        - BearerAuth: []
      parameters:
        - name: offset
          in: query
          description: offset information
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Limit information
          required: false
          schema:
            type: string
        - name: email
          in: query
          description: query email infomation
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: query name information
          required: false
          schema:
            type: string
        - name: organization
          in: query
          description: query organization information
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: query user status
          required: false
          schema:
            type: integer
        - name: group_id
          in: query
          description: query group ID
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users.GetUsersResponse'
        '401':
          description: Unauthorized
        '403':
          description: 'Not authorized : user is not admin'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal Server Error
  /users/{user_id}:
    put:
      tags:
        - user
      summary: update user status
      description: update user status
      operationId: updatetUserStatusById
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users.UpdateUserStatusRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users.GetOneUserResponse'
        '401':
          description: Unauthorized
        '403':
          description: Not authorized
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: User not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal Server Error
    delete:
      tags:
        - user
      summary: delete user
      description: delete user with designated id
      operationId: deleteUserById
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Success
        '403':
          description: Not authorized
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: User not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal Server Error
  /whitelist:
    get:
      tags:
        - WhitelistUsers
      summary: List whitelist users
      description: List whitelist users
      operationId: listWhitelistUsers
      security:
        - BearerAuth: []
      parameters:
        - name: offset
          in: query
          description: offset information
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Limit information
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Return a list of whitelist users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/whitelist_users.ListWhitelistUsersResponse'
        '401':
          description: Unauthorized
        '403':
          description: 'Not authorized : user is not admin'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
    post:
      tags:
        - WhitelistUsers
      summary: register a user to the whitelist
      description: register a user to the whitelist
      operationId: registerWhitelistUser
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/whitelist_users.RegisterWhitelistUsersRequest'
      responses:
        '200':
          description: Success register a user to the whitelist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success.SuccessResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequestError'
        '401':
          description: Unauthorized
        '403':
          description: 'Not authorized : user is not admin'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
    delete:
      tags:
        - WhitelistUsers
      summary: delete a user from the whitelist
      description: delete a user from the whitelist
      operationId: deleteWhitelistUser
      security:
        - BearerAuth: []
      parameters:
        - name: user_emails
          in: query
          description: email of the user to be deleted
          required: true
          schema:
            $ref: '#/components/schemas/whitelist_users.WhitelistUsersDeleteRequest'
      responses:
        '204':
          description: Delete success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success.SuccessResponse'
        '401':
          description: Unauthorized
        '403':
          description: 'Not authorized : user is not admin'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    users.GetOneUserResponse:
      description: detail of users response
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        name:
          type: string
        organization:
          type: string
        status:
          type: string
        group_id:
          type: string
        require_mfa_reset:
          type: boolean
      xml:
        name: User
      required:
        - id
    users.GetUsersResponse:
      properties:
        offset:
          type: string
        limit:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/users.GetOneUserResponse'
    error.InternalServerError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    users.UpdateUserStatusRequest:
      type: object
      properties:
        status:
          type: string
    error.NotFoundError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    whitelist_users.Email:
      type: string
      example: example@example.com
    whitelist_users.ListWhitelistUserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        group_id:
          type: string
          example: group1
        email:
          $ref: '#/components/schemas/whitelist_users.Email'
        username:
          type: string
          example: exampleuser
        organization:
          type: string
          example: Example Organization
        is_signup_completed:
          type: boolean
          example: true
      required:
        - id
        - group_id
        - email
      example:
        id: 1
        group_id: group1
        email: example@example.com
        username: exampleuser
        organization: Example Organization
        is_signup_completed: true
    whitelist_users.ListWhitelistUsersResponse:
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/whitelist_users.ListWhitelistUserResponse'
    whitelist_users.RegisterWhitelistUserRequest:
      description: Whitelist user register request
      type: object
      properties:
        group_id:
          type: string
        email:
          type: string
        username:
          type: string
        organization:
          type: string
    whitelist_users.RegisterWhitelistUsersRequest:
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/whitelist_users.RegisterWhitelistUserRequest'
    success.SuccessResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    error.BadRequestError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    whitelist_users.WhitelistUsersDeleteRequest:
      properties:
        user_emails:
          type: array
          items:
            $ref: '#/components/schemas/whitelist_users.Email'
