# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - curl -Ls https://astral.sh/uv/install.sh | bash
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - $HOME/.cargo/bin/uv pip install --with docs

# Build documentation with mkdocs
mkdocs:
  configuration: mkdocs.yaml
