jobs:
  get:
    tags:
      - jobs
    summary: Search jobs for a device
    description: Search jobs for a device
    operationId: getjobs
    security: []
    parameters:
        - in: query
          name: device_id
          required: true
          description: "Device identifier"
          schema: {type: string, example: "Kawasaki"}
        - in: query
          name: status
          description: "Additional search parameter:<br/> Search jobs with specified status only"
          schema:
            $ref: "../schemas/jobs.yaml#/jobs.InternalJobStatus"
        - in: query
          name: max_results
          description: "Additional search parameter:<br/> Set max number of quantum jobs to return in single request"
          schema: {type: integer, example: 1}
        - in: query
          name: timestamp
          description: "Additional search parameter:<br/> Fetch jobs created after the specified timetsamp"
          schema: {type: string, example: '2022-12-15 15:54:46'}
    responses:
      "200":
        description: "List of jobs for a device"
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../schemas/jobs.yaml#/jobs.JobDef"
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.BadRequest'
            example:
              detail: Bad request malformed input data
      '500':
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.InternalServerError'
            example:
              detail: Internal server error

jobs.jobId:
  get:
    summary: Get a job by ID
    description: Get a job by ID
    operationId: getJob
    security: []
    tags:
    - jobs
    parameters:
        - in: path
          name: job_id
          required: true
          description: "Job identifier"
          schema: {type: string}
    responses:
      "200":
        description: "Return quantum job"
        content:
          application/json:
            schema:
              $ref: "../schemas/jobs.yaml#/jobs.JobDef"
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.BadRequest'
            example:
              detail: Bad request malformed input data
      '404':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.NotFoundError'
            example:
              detail: job not found
  patch:
    summary: "Modify selected quantum job (update status)."
    description: "Used by device to set job status to \"RUNNING\".<br/>Other statuses are set by CloudAPI automatically when result is created"
    operationId: patchJob
    security: []
    tags:
      - jobs
    parameters:
        - in: path
          name: job_id
          required: true
          description: "Job identifier"
          schema: {type: string}
    requestBody:
      description: "New job status. "
      content:
        application/json:
          schema:
            $ref: "../schemas/jobs.yaml#/jobs.JobStatusUpdate"
    responses:
      '200':
        description: job data updated
        content:
          application/json:
            schema:
              $ref: '../schemas/jobs.yaml#/jobs.JobStatusUpdateResponse'
            example:
              message: job data updated
      "400":
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.BadRequest'
            example:
              detail: Bad request malformed input data
      "404":
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.NotFoundError'
            example:
              detail: job not found

jobs.unfetched:
  get:
    summary: "Fetch jobs for device"
    description: "Fetches jobs for execution/cancel<br/><br/>Operation is valid only for job with status: submitted or cancelling. After the operation job status is changed to appropriate ready state (submitted or cancelled)"
    operationId: getUnfetchedJobs
    security: []
    tags:
    - jobs
    parameters:
      - in: query
        name: device_id
        required: true
        description: "Device identifier"
        schema: {type: string, example: "Kawasaki"}
      - in: query
        name: status
        required: true
        description: "Fetch jobs with specified status"
        schema:
          $ref: "../schemas/jobs.yaml#/jobs.InternalFetchableJobStatus"
      - in: query
        name: max_results
        description: "Additional search parameter:<br/> Set max number of quantum jobs to return in single request"
        schema: {type: integer, example: 1}

    responses:
      "200":
        description: "List of jobs for execution (all job data) / cancel (jobIds only)"
        content:
          application/json:
            schema:
              $ref: "../schemas/jobs.yaml#/jobs.UnfetchedJobsResponse"
      "400":
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../schemas/error.yaml#/error.BadRequest'
            example:
              detail: Bad request malformed input data
