# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel, EmailStr


class ConfirmationSignupRequest(BaseModel):
    email: EmailStr
    """
    The email address of the user
    """
    confirmation_code: str
    """
    The confirmation code sent to the user
    """
