# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel, EmailStr


class MfaResetStartRequest(BaseModel):
    email: EmailStr
    password: str


class MfaResetVerifyCodeRequest(BaseModel):
    email: EmailStr
    password: str
    code: str


class MfaResetVerifyCodeResponse(BaseModel):
    secret: str | None = None
    """
    Base32 encoded secret for TOTP
    """


class MfaResetConfirmTotpRequest(BaseModel):
    email: EmailStr
    password: str
    totp_code: str
