# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel


class MfaResetRequest(BaseModel):
    email: str
    """
    The email of the user
    """
    password: str
    """
    The password of the user
    """
    client_id: str
    """
    The client id of the user
    """
