# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel, EmailStr


class MfaResetStartRequest(BaseModel):
    email: EmailStr
    password: str


class MfaResetStartResponse(BaseModel):
    access_token: str | None = None
    """
    Access token to access Cognito API
    """


class MfaResetVerifyCodeRequest(BaseModel):
    access_token: str
    code: str


class MfaResetVerifyCodeResponse(BaseModel):
    secret: str | None = None
    """
    Base32 encoded secret for TOTP
    """


class MfaResetConfirmTotpRequest(BaseModel):
    access_token: str
    totp_code: str
