# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class GetAnnouncementResponse(BaseModel):
    id: Annotated[int, Field(examples=[0])]
    title: Annotated[str, Field(examples=["Example Title"])]
    content: Annotated[str, Field(examples=["Example Content"])]
    start_time: Annotated[AwareDatetime, Field(examples=["2022-10-19T11:45:34Z"])]
    end_time: Annotated[AwareDatetime, Field(examples=["2022-12-19T11:45:34Z"])]
    publishable: Annotated[bool, Field(examples=[True])]


class GetAnnouncementsListResponse(BaseModel):
    announcements: list[GetAnnouncementResponse] | None = None
