# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, Field


class ApiToken(BaseModel):
    api_token_secret: str | None = None
    """
    The api token secret
    """
    api_token_expiration: Annotated[
        datetime | None, Field(examples=["2025-01-09T12:34:56"])
    ] = None
    """
    The expiration date of the api token
    """
