# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class DeviceType(str, Enum):
    QPU = "QPU"
    simulator = "simulator"


class Status(str, Enum):
    available = "available"
    unavailable = "unavailable"


class DeviceInfo(BaseModel):
    device_id: Annotated[str | None, Field(examples=["SVSim"])] = None
    device_type: Annotated[DeviceType | None, Field(examples=["simulator"])] = None
    status: Annotated[Status, Field(examples=["available"])]
    available_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    """
    Parameter mandatory and valid for 'unavailable' devices
    """
    n_pending_jobs: Annotated[int | None, Field(examples=[8])] = None
    n_qubits: Annotated[int | None, Field(examples=[39])] = None
    basis_gates: Annotated[
        list[str] | None,
        Field(
            examples=[
                [
                    "x",
                    "y",
                    "z",
                    "h",
                    "s",
                    "sdg",
                    "t",
                    "tdg",
                    "rx",
                    "ry",
                    "rz",
                    "cx",
                    "cz",
                    "swap",
                    "u1",
                    "u2",
                    "u3",
                    "u",
                    "p",
                    "id",
                    "sx",
                    "sxdg",
                ]
            ]
        ),
    ] = None
    supported_instructions: Annotated[
        list[str] | None, Field(examples=[["measure", "barrier", "reset"]])
    ] = None
    device_info: Annotated[
        str | None,
        Field(
            examples=[
                "{'n_nodes': 512, 'calibration_data': {'qubit_connectivity': ['(1,4)', '(4,5)', '(5,8)'], 't1': {'0': 55.51, '1': 37.03, '2': 57.13}}"
            ]
        ),
    ] = None
    """
    json format calibration_data and n_nodes etc
    """
    calibrated_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    """
    Parameter available only for 'QPU' devices with available calibration data
    """
    description: Annotated[
        str, Field(examples=["State vector-based quantum circuit simulator"])
    ]
