# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel


class UnauthorizedError(BaseModel):
    message: str


class InternalServerError(BaseModel):
    message: str


class ForbiddenError(BaseModel):
    message: str


class NotFoundError(BaseModel):
    message: str


class BadRequest(BaseModel):
    message: str
