# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class JobStatus(Enum):
    submitted = "submitted"
    ready = "ready"
    running = "running"
    success = "success"
    failed = "failed"
    cancelled = "cancelled"


class JobDef(BaseModel):
    job_id: Annotated[
        Optional[str], Field(None, examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])
    ]
    name: Annotated[Optional[str], Field(None, examples=["Bell State Sampling"])]
    description: Annotated[
        Optional[str], Field(None, examples=["Bell State Sampling Example"])
    ]
    device_id: Annotated[str, Field(examples=["Kawasaki"])]
    shots: Annotated[int, Field(examples=["1000"], ge=1, le=10000000)]
    job_type: Annotated[
        Optional[str], Field(None, examples=["'sampling' or 'estimation', 'sse'"])
    ]
    job_info: Annotated[
        Optional[str],
        Field(
            None,
            examples=[
                "{'code': '{type: string, example: \"OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;\"}', 'Operator': 'X 0 Y 1 Z 5 I 2', 'result': {'00': 5020, '11': 4980}, 'transpiledCode': '', 'reason': ''}"
            ],
        ),
    ]
    transpiler_info: Annotated[
        Optional[str],
        Field(
            None,
            examples=[
                "{'qubitAllocation': {'0': 12, '1': 16}, 'skipTranspilation': false, 'seedTranspilation': 873}"
            ],
        ),
    ]
    simulator_info: Annotated[
        Optional[str],
        Field(
            None,
            examples=[
                "{'nQubits': 5, 'nNodes': 12, 'nPerNode': 2, 'seedSimulation': 39058567, 'simulationOpt': {'optimizationMethod': 'light', 'optimizationBlockSize': 1, 'optimizationSwapLevel': 1}}"
            ],
        ),
    ]
    mitigation_info: Annotated[
        Optional[str], Field(None, examples=["{'roErrorMitigation': 'pseudo_inverse'}"])
    ]
    status: JobStatus
    created_at: Annotated[AwareDatetime, Field(examples=["2022-10-19T11:45:34+09:00"])]
    updated_at: Annotated[
        Optional[AwareDatetime], Field(None, examples=["2022-10-19T11:45:34+09:00"])
    ]


class SubmitJobResponse(BaseModel):
    """
    submit a job
    """

    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]


class GetJobStatusResponse(BaseModel):
    """
    job status
    """

    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    status: JobStatus
