# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class S3TranspileResult(BaseModel):
    transpiled_program: Annotated[
        str | None,
        Field(
            examples=[
                'OPENQASM 3; include "stdgates.inc"; qubit[2] _all_qubits; let q = _all_qubits[0:1]; h q[0]; cx q[0], q[1];'
            ]
        ),
    ] = None
    stats: Annotated[dict[str, Any] | None, Field(...)]
    virtual_physical_mapping: Annotated[dict[str, Any] | None, Field(...)]


class JobType(str, Enum):
    """
    none is valid only for newly registered job_ids (job status=registered)
    """

    none = "none"
    estimation = "estimation"
    sampling = "sampling"
    multi_manual = "multi_manual"
    sse = "sse"


class JobStatus(str, Enum):
    registered = "registered"
    submitted = "submitted"
    ready = "ready"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class JobInfo(BaseModel):
    """
    Presigned URLs for downloading relevant job information .zip files from OQTOPUS cloud.
    """

    input: Annotated[
        str,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D"
            ]
        ),
    ]
    """
    Presigned URL for downloading a file from OCTOPUS cloud.
    """
    combined_program: Annotated[
        str | None,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D"
            ]
        ),
    ] = None
    """
    Presigned URL for downloading a file from OCTOPUS cloud.
    """
    result: Annotated[
        str | None,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D"
            ]
        ),
    ] = None
    """
    Presigned URL for downloading a file from OCTOPUS cloud.
    """
    transpile_result: Annotated[
        str | None,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D"
            ]
        ),
    ] = None
    """
    Presigned URL for downloading a file from OCTOPUS cloud.
    """
    sse_log: Annotated[
        str | None,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D"
            ]
        ),
    ] = None
    """
    Presigned URL for downloading a file from OCTOPUS cloud.
    """


class JobBase(BaseModel):
    job_id: Annotated[
        str | None, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])
    ] = None
    name: Annotated[str | None, Field(examples=["Bell State Sampling"])] = None
    description: Annotated[
        str | None, Field(examples=["Bell State Sampling Example"])
    ] = None
    job_type: JobType | None = None
    status: JobStatus | None = None
    device_id: Annotated[str | None, Field(examples=["Kawasaki"])] = None
    shots: Annotated[int | None, Field(examples=["1000"], ge=0, le=10000000)] = None
    """
    0 is valid only for newly registered job_ids (job status=registered)
    """
    job_info: JobInfo | None = None
    transpiler_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "qubit_allocation": {"0": 12, "1": 16},
                    "skip_transpilation": False,
                    "seed_transpilation": 873,
                }
            ]
        ),
    ] = None
    simulator_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "n_qubits": 5,
                    "n_nodes": 12,
                    "n_per_node": 2,
                    "seed_simulation": 39058567,
                    "simulation_opt": {
                        "optimization_method": "light",
                        "optimization_block_size": 1,
                        "optimization_swap_level": 1,
                    },
                }
            ]
        ),
    ] = None
    mitigation_info: Annotated[
        dict[str, Any] | None,
        Field(examples=[{"ro_error_mitigation": "pseudo_inverse"}]),
    ] = None
    execution_time: Annotated[float | None, Field(examples=["10.123"])] = None
    submitted_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    ready_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    running_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    ended_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None


class Fields(BaseModel):
    key: Annotated[
        str | None,
        Field(examples=["jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip"]),
    ] = None
    AWSAccessKeyId: str | None = None
    x_amz_security_token: Annotated[str | None, Field(alias="x-amz-security-token")] = (
        None
    )
    policy: str | None = None
    signature: str | None = None


class JobInfoUploadPresignedURL(BaseModel):
    """
    Presigned URL for uploading file to OCTOPUS cloud.
    """

    url: Annotated[
        str | None, Field(examples=["https://oqtopus-cloud.s3.amazonaws.com/"])
    ] = None
    fields: Fields | None = None


class RegisterJobResponse(BaseModel):
    """
    Register new job
    """

    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    presigned_url: JobInfoUploadPresignedURL


class SubmittedJob(JobBase):
    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    name: Annotated[str, Field(examples=["Bell State Sampling"])]
    job_type: JobType
    status: JobStatus
    device_id: Annotated[str, Field(examples=["Kawasaki"])]
    shots: Annotated[int, Field(examples=["1000"], ge=0, le=10000000)]
    """
    0 is valid only for newly registered job_ids (job status=registered)
    """
    job_info: JobInfo


class RegisteredJob(JobBase):
    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    status: JobStatus


class SubmitJobType(str, Enum):
    estimation = "estimation"
    sampling = "sampling"
    multi_manual = "multi_manual"
    sse = "sse"


class SubmitJobRequest(BaseModel):
    name: Annotated[str | None, Field(examples=["Bell State Sampling"])] = None
    description: Annotated[
        str | None, Field(examples=["An example of Bell state sampling job"])
    ] = None
    device_id: Annotated[str, Field(examples=["Kawasaki"])]
    job_type: SubmitJobType
    transpiler_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "qubit_allocation": {"0": 12, "1": 16},
                    "skip_transpilation": False,
                    "seed_transpilation": 873,
                }
            ]
        ),
    ] = None
    simulator_info: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "n_qubits": 5,
                    "n_nodes": 12,
                    "n_per_node": 2,
                    "seed_simulation": 39058567,
                    "simulation_opt": {
                        "optimization_method": "light",
                        "optimization_block_size": 1,
                        "optimization_swap_level": 1,
                    },
                }
            ]
        ),
    ] = None
    mitigation_info: Annotated[
        dict[str, Any] | None,
        Field(examples=[{"ro_error_mitigation": "pseudo_inverse"}]),
    ] = None
    shots: Annotated[int, Field(examples=[1000], ge=1, le=10000000)]


class GetJobStatusResponse(BaseModel):
    """
    job status
    """

    job_id: Annotated[str, Field(examples=["7af020f6-2e38-4d70-8cf0-4349650ea08c"])]
    status: JobStatus


class GetSselogResponse(BaseModel):
    """
    sse log file
    """

    file: str | None = None
    file_name: Annotated[
        str | None, Field(examples=["sselog_7af020f6-2e38-4d70-8cf0-4349650ea08c.zip"])
    ] = None


class S3OperatorItem(BaseModel):
    pauli: Annotated[str, Field(examples=["X 0 X 1"])]
    """
    The Pauli string.
    """
    coeff: Annotated[float | None, Field(examples=[1])] = None
    """
    Coefficient number in the Pauli string representation.
    """


class S3SamplingResult(BaseModel):
    """
    *(Only for sampling jobs)* JSON string representing the sampling result
    """

    counts: Annotated[
        dict[str, Any] | None,
        Field(examples=[{"10": 454, "11": 387, "00": 84, "01": 75}]),
    ] = None
    divided_counts: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {
                    "0": {"10": 454, "11": 387, "00": 84, "01": 75},
                    "1": {"10": 454, "11": 387, "00": 84, "01": 75},
                }
            ]
        ),
    ] = None


class S3EstimationResult(BaseModel):
    """
    *(Only for estimation jobs)* The estimated expectation value and the standard deviation
    of the operators specified in `job_info.operator` field which is intended to be provided for estimation jobs.

    """

    exp_value: float | None = None
    """
    The estimated expectation value
    """
    stds: float | None = None
    """
    The standard deviation value
    """


class S3SubmitJobInfo(BaseModel):
    program: Annotated[
        list[str],
        Field(
            examples=[
                '[ "OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;" ]'
            ]
        ),
    ]
    """
    A list of OPENQASM3 program. For non-multiprogramming jobs, this field is assumed to contain exactly one program. Otherwise, those programs are combined according to the multiprogramming machinery.
    """
    operator: list[S3OperatorItem] | None = None


class S3JobResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    sampling: S3SamplingResult | None = None
    estimation: S3EstimationResult | None = None
