# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class EditableField(str, Enum):
    name = "name"
    organization = "organization"


class VisibleField(str, Enum):
    id = "id"
    name = "name"
    email = "email"
    organization = "organization"
    created_at = "created_at"


class GetSettingsResponse(BaseModel):
    """
    detail of settings response
    """

    editable_fields: list[EditableField]
    allow_deletion: bool
    visible_fields: list[VisibleField]
    login_history_enabled: bool
