# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-08-29T08:54:22+00:00
#   version:   0.25.8

from __future__ import annotations

from pydantic import BaseModel


class SuccessResponse(BaseModel):
    message: str
