# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class LoginEvent(BaseModel):
    """
    details of login event
    """

    event_date: AwareDatetime | None = None
    user_agent: str | None = None
    ip: str | None = None


class GetOneUserResponse(BaseModel):
    """
    detail of user response
    """

    id: int
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    created_at: AwareDatetime | None = None
    login_events: list[LoginEvent] | None = None


class UpdateUserRequest(BaseModel):
    """
    user update data
    """

    name: str | None = None
    organization: str | None = None
