# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class GetOneUserResponse(BaseModel):
    """
    detail of user response
    """

    id: int
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    created_at: AwareDatetime | None = None


class UpdateUserRequest(BaseModel):
    """
    user update data
    """

    name: str | None = None
    organization: str | None = None
