settings.GetSettingsResponse:
  description: detail of settings response
  type: object
  properties:
    editable_fields:
      type: array
      items:
        type: string
        enum:
          - 'name'
          - 'organization'
    allow_deletion:
      type: boolean
    visible_fields:
      type: array
      items:
        type: string
        enum:
          - id
          - name
          - email
          - organization
          - created_at
    login_history_enabled:
      type: boolean
  required:
    - editable_fields
    - allow_deletion
    - visible_fields
    - login_history_enabled