"""create devices

Revision ID: 38a0365a40fd
Revises:
Create Date: 2024-09-11 16:35:08.445166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38a0365a40fd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("device_type", sa.String(length=128), nullable=False),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.Column("restart_at", sa.DateTime(), nullable=True),
        sa.Column("pending_tasks", sa.Integer(), nullable=False),
        sa.Column("n_qubits", sa.Integer(), nullable=False),
        sa.Column("n_nodes", sa.Integer(), nullable=True),
        sa.Column("basis_gates", sa.String(length=256), nullable=False),
        sa.Column("instructions", sa.String(length=64), nullable=False),
        sa.Column("calibration_data", sa.Text(), nullable=False),
        sa.Column("calibrated_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    # ### end Alembic commands ###
