"""create_quantum_gates

Revision ID: dcb77f1319fd
Revises: 9b835b4d8801
Create Date: 2024-09-13 16:49:39.753049

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "dcb77f1319fd"
down_revision: Union[str, None] = "9b835b4d8801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quantum_gates",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("n_qubits", sa.Integer(), nullable=False),
        sa.Column("n_clbits", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gate_supports",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("gate_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["quantum_gates.id"],
        ),
        sa.PrimaryKeyConstraint("device_id", "gate_id"),
    )
    op.drop_column("devices", "basis_gates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "basis_gates",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
            nullable=False,
        ),
    )
    op.drop_table("gate_supports")
    op.drop_table("quantum_gates")
    # ### end Alembic commands ###
