"""set_jobs_status_default

Revision ID: 6bd5dd2dc2ce
Revises: 4259239bd704
Create Date: 2024-12-27 15:56:56.786646

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6bd5dd2dc2ce"
down_revision: Union[str, None] = "4259239bd704"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "status",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        server_default="submitted",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "status",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
