"""Initial

Revision ID: 8c694dc91377
Revises: 
Create Date: 2025-06-17 20:55:56.400462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c694dc91377'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('publishable', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), server_default='QPU', nullable=False),
    sa.Column('status', sa.String(length=64), server_default='available', nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('pending_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('n_qubits', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('basis_gates', sa.String(length=256), nullable=False),
    sa.Column('instructions', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), server_default='', nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='submitted', nullable=False),
    sa.Column('job_type', sa.String(length=32), server_default='sampling', nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('shots', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('execution_time', sa.DECIMAL(precision=65, scale=3), nullable=True),
    sa.Column('job_info', sa.Text(), nullable=True),
    sa.Column('transpiler_info', sa.Text(), nullable=True),
    sa.Column('simulator_info', sa.Text(), nullable=True),
    sa.Column('mitigation_info', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('running_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cognito_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('userstatus', sa.String(length=10), nullable=True),
    sa.Column('api_token_secret', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('api_token_expiration', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token_secret'),
    sa.UniqueConstraint('cognito_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('whitelist_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=False),
    sa.Column('is_signup_completed', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist_users')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_table('devices')
    op.drop_table('announcements')
    # ### end Alembic commands ###
