"""initial_schema

Revision ID: fc532120ca03
Revises: 
Create Date: 2026-05-21 07:46:33.686204+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from oqtopus_cloud.common.model_util import DateTimeTz
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc532120ca03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_time', DateTimeTz(), nullable=True),
    sa.Column('end_time', DateTimeTz(), nullable=True),
    sa.Column('publishable', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), server_default='QPU', nullable=False),
    sa.Column('status', sa.String(length=64), server_default='available', nullable=False),
    sa.Column('available_at', DateTimeTz(), nullable=True),
    sa.Column('pending_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('n_qubits', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('basis_gates', sa.String(length=256), nullable=False),
    sa.Column('instructions', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=False),
    sa.Column('calibrated_at', DateTimeTz(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('created_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), server_default='', nullable=True),
    sa.Column('description', sa.String(length=1024), server_default='', nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('transpiler_info', sa.Text(), nullable=False),
    sa.Column('simulator_info', sa.Text(), nullable=False),
    sa.Column('mitigation_info', sa.Text(), nullable=False),
    sa.Column('job_type', sa.String(length=32), server_default='sampling', nullable=False),
    sa.Column('shots', sa.Integer(), server_default=sa.text('(1000)'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='submitted', nullable=False),
    sa.Column('execution_time', sa.Numeric(precision=65, scale=3), nullable=True),
    sa.Column('output_files', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('submitted_at', DateTimeTz(), nullable=True),
    sa.Column('ready_at', DateTimeTz(), nullable=True),
    sa.Column('running_at', DateTimeTz(), nullable=True),
    sa.Column('ended_at', DateTimeTz(), nullable=True),
    sa.Column('created_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('cognito_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('userstatus', sa.String(length=10), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('available_devices', sa.Text(), nullable=True),
    sa.Column('mfa_status', sa.String(length=255), server_default='disabled', nullable=False),
    sa.Column('api_token_id', sa.String(length=255), nullable=True),
    sa.Column('api_token_hash', sa.String(length=255), nullable=True),
    sa.Column('api_token_expiration', DateTimeTz(), nullable=True),
    sa.Column('created_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token_id'),
    sa.UniqueConstraint('cognito_id')
    )
    op.create_table('whitelist_users',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_signup_completed', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('available_devices', sa.Text(), nullable=True),
    sa.Column('created_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', DateTimeTz(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    # MySQL-only: apply `ON UPDATE CURRENT_TIMESTAMP` to every `updated_at`
    # column. SQLAlchemy cannot express this clause at the model level, so we
    # emit raw DDL here. No-op on SQLite tests.
    bind = op.get_bind()
    if bind.dialect.name == "mysql":
        for _table in ("devices", "jobs", "users", "whitelist_users", "announcements"):
            op.execute(
                f"ALTER TABLE {_table} "
                f"MODIFY updated_at TIMESTAMP NULL "
                f"DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist_users')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_table('devices')
    op.drop_table('announcements')
    # ### end Alembic commands ###
