"""drop devices device_info

Revision ID: 676e54a5dbaf
Revises: fc532120ca03
Create Date: 2026-07-07 05:23:45.727614+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676e54a5dbaf'
down_revision: Union[str, Sequence[str], None] = 'fc532120ca03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_info', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
