openapi: 3.0.1
info:
  title: OQTOPUS Cloud Provider API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8888
    description: Local server url
paths:
  /devices/{device_id}:
    $ref: ./paths/devices.yaml#/devices.deviceId
  /jobs:
    $ref: ./paths/jobs.yaml#/jobs
  /jobs/{job_id}:
    $ref: ./paths/jobs.yaml#/jobs.jobId
  /jobs/unfetched:
    $ref: ./paths/jobs.yaml#/jobs.unfetched
