openapi: 3.0.1
info:
  title: OQTOPUS Cloud User API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server url
paths:
  /devices:
    $ref: ./paths/devices.yaml#/devices
  /devices/{deviceId}:
    $ref: ./paths/devices.yaml#/devices.deviceId
  /jobs:
    $ref: ./paths/jobs.yaml#/jobs
  /jobs/{jobId}:
    $ref: ./paths/jobs.yaml#/jobs.jobId
  /jobs/{jobId}/status:
    $ref: ./paths/jobs.yaml#/jobs.jobId.status
  /jobs/{jobId}/cancel:
    $ref: ./paths/jobs.yaml#/jobs.jobId.cancel

components:
  securitySchemes:
    BearerAuth:
      $ref: './schemas/security.yaml#/BearerAuth'
