openapi: 3.0.1
info:
  title: OQTOPUS Cloud User API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: ${API_SERVER_URL}
    description: ${API_SERVER_DESCRIPTION}
paths:
  /devices:
    $ref: ./paths/devices.yaml#/devices
  /devices/{device_id}:
    $ref: ./paths/devices.yaml#/devices.device_id
  /device_histories:
    $ref: ./paths/devices.yaml#/device_histories
  /device_histories/{history_uid}:
    $ref: ./paths/devices.yaml#/device_histories.history_uid
  /jobs:
    $ref: ./paths/jobs.yaml#/jobs
  /jobs/{job_id}/submit:
    $ref: ./paths/jobs.yaml#/jobs.job_id.submit
  /jobs/{job_id}:
    $ref: ./paths/jobs.yaml#/jobs.job_id
  /jobs/{job_id}/status:
    $ref: ./paths/jobs.yaml#/jobs.job_id.status
  /jobs/{job_id}/cancel:
    $ref: ./paths/jobs.yaml#/jobs.job_id.cancel
  /api-token:
    $ref: ./paths/api-token.yaml#/api-token
  /api-token/status:
    $ref: ./paths/api-token.yaml#/api-token.status
  /announcements:
    $ref: ./paths/announcements.yaml#/announcements
  /announcements/{announcement_id}:
    $ref: ./paths/announcements.yaml#/announcements.announcement_id
  /users/me:
    $ref: ./paths/users.yaml#/users.me
  /system/settings:
    $ref: ./paths/system-settings.yaml#/system.settings
components:
  securitySchemes:
    BearerAuth:
      $ref: ./schemas/security.yaml#/BearerAuth
  schemas:
    # below schemas are not used directly in OAS,
    # but the generated classed definitions are used in API and SDK implementation
    jobs.SubmittedJob:
      $ref: ./schemas/jobs.yaml#/jobs.SubmittedJob
    jobs.RegisteredJob:
      $ref: ./schemas/jobs.yaml#/jobs.RegisteredJob
    jobs.S3SubmitJobInfo:
      $ref: ./schemas/jobs.yaml#/jobs.S3SubmitJobInfo
    jobs.S3JobResult:
      $ref: ./schemas/jobs.yaml#/jobs.S3JobResult
    jobs.S3TranspileResult:
      $ref: ./schemas/jobs.yaml#/jobs.S3TranspileResult
