openapi: 3.0.1
info:
  title: OQTOPUS Cloud User API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: ${API_SERVER_URL}
    description: ${API_SERVER_DESCRIPTION}
paths:
  /signup:
    $ref: ./paths/signup.yaml#/signup
  /confirm:
    $ref: ./paths/confirm_signup.yaml#/confirm_signup
  /mfa_reset_request:
    $ref: ./paths/mfa_reset_request.yaml#/mfa_reset_request
  /mfa_reset/start:
    $ref: ./paths/mfa_reset.yaml#/mfa_reset.start
  /mfa_reset/verify_code:
    $ref: ./paths/mfa_reset.yaml#/mfa_reset.verify_code
  /mfa_reset/confirm_totp:
    $ref: ./paths/mfa_reset.yaml#/mfa_reset.confirm_totp

components:
  securitySchemes:
    BearerAuth:
      $ref: './schemas/security.yaml#/BearerAuth'
