# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class DeviceType(str, Enum):
    QPU = "QPU"
    simulator = "simulator"


class Status(str, Enum):
    available = "available"
    unavailable = "unavailable"


class DeviceInfo(BaseModel):
    device_id: Annotated[str, Field(examples=["SVSim"])]
    device_type: Annotated[DeviceType, Field(examples=["simulator"])]
    status: Annotated[Status, Field(examples=["available"])]
    available_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34"])
    ] = None
    """
    Parameter mandatory and valid for 'unavailable' devices
    """
    n_pending_jobs: Annotated[int, Field(examples=[8])]
    n_qubits: Annotated[int | None, Field(examples=[64])] = None
    basis_gates: Annotated[
        list[str],
        Field(
            examples=[
                [
                    "x",
                    "y",
                    "z",
                    "h",
                    "s",
                    "sdg",
                    "t",
                    "tdg",
                    "rx",
                    "ry",
                    "rz",
                    "cx",
                    "cz",
                    "swap",
                    "u1",
                    "u2",
                    "u3",
                    "u",
                    "p",
                    "id",
                    "sx",
                    "sxdg",
                ]
            ]
        ),
    ]
    supported_instructions: Annotated[
        list[str], Field(examples=[["measure", "barrier", "reset"]])
    ]
    device_info: str | None = None
    """
    json format calibration_data and n_nodes etc
    """
    calibrated_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34"])
    ] = None
    """
    Parameter available only for `QPU` devices with available calibration data
    """
    description: Annotated[
        str, Field(examples=["State vector-based quantum circuit simulator"])
    ]


class DeviceBase(BaseModel):
    device_info: Annotated[
        str | None, Field(examples=['{"device_id": "Kawasaki", "qubits": []}'])
    ] = None
    device_type: Annotated[DeviceType | None, Field(examples=["simulator"])] = None
    status: Annotated[Status | None, Field(examples=["available"])] = None
    n_qubits: Annotated[int | None, Field(examples=[64])] = None
    available_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34"])
    ] = None
    calibrated_at: Annotated[
        datetime | None, Field(examples=["2022-10-19T11:45:34"])
    ] = None
    basis_gates: Annotated[
        str | None,
        Field(
            examples=[
                '["x", "y", "z", "h", "s", "sdg", "t", "tdg", "rx", "ry", "rz", "cx", "cz", "swap", "u1", "u2", "u3", "u", "p", "id", "sx", "sxdg"]'
            ]
        ),
    ] = None
    supported_instructions: Annotated[
        str | None, Field(examples=['["measure", "barrier", "reset"]'])
    ] = None
    description: Annotated[
        str | None, Field(examples=["Superconducting quantum computer"])
    ] = None
