# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field


class DeviceType(str, Enum):
    QPU = "QPU"
    simulator = "simulator"


class Status(str, Enum):
    available = "available"
    unavailable = "unavailable"


class DeviceInfo(BaseModel):
    device_id: Annotated[str, Field(examples=["SVSim"])]
    device_type: Annotated[DeviceType, Field(examples=["simulator"])]
    status: Annotated[Status, Field(examples=["available"])]
    available_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    """
    Parameter mandatory and valid for 'unavailable' devices
    """
    n_pending_jobs: Annotated[int, Field(examples=[8])]
    n_qubits: Annotated[int | None, Field(examples=[64])] = None
    basis_gates: Annotated[
        list[str],
        Field(
            examples=[
                [
                    "x",
                    "y",
                    "z",
                    "h",
                    "s",
                    "sdg",
                    "t",
                    "tdg",
                    "rx",
                    "ry",
                    "rz",
                    "cx",
                    "cz",
                    "swap",
                    "u1",
                    "u2",
                    "u3",
                    "u",
                    "p",
                    "id",
                    "sx",
                    "sxdg",
                ]
            ]
        ),
    ]
    supported_instructions: Annotated[
        list[str], Field(examples=[["measure", "barrier", "reset"]])
    ]
    device_info: str | None = None
    """
    json format calibration_data and n_nodes etc
    """
    calibrated_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    """
    Parameter available only for `QPU` devices with available calibration data
    """
    description: Annotated[
        str, Field(examples=["State vector-based quantum circuit simulator"])
    ]


class DeviceBase(BaseModel):
    device_info: Annotated[
        str | None, Field(examples=['{"device_id": "qulacs", "qubits": []}'])
    ] = None
    device_type: Annotated[DeviceType | None, Field(examples=["simulator"])] = None
    status: Annotated[Status | None, Field(examples=["available"])] = None
    n_qubits: Annotated[int | None, Field(examples=[64])] = None
    available_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    calibrated_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    basis_gates: Annotated[
        list[str] | None,
        Field(
            examples=[
                [
                    "x",
                    "y",
                    "z",
                    "h",
                    "s",
                    "sdg",
                    "t",
                    "tdg",
                    "rx",
                    "ry",
                    "rz",
                    "cx",
                    "cz",
                    "swap",
                    "u1",
                    "u2",
                    "u3",
                    "u",
                    "p",
                    "id",
                    "sx",
                    "sxdg",
                ]
            ]
        ),
    ] = None
    supported_instructions: Annotated[
        list[str] | None, Field(examples=[["measure", "barrier", "reset"]])
    ] = None
    description: Annotated[
        str | None, Field(examples=["Superconducting quantum computer"])
    ] = None


class DevicePatch(BaseModel):
    device_type: Annotated[DeviceType | None, Field(examples=["simulator"])] = None
    status: Annotated[Status | None, Field(examples=["available"])] = None
    n_qubits: Annotated[int | None, Field(examples=[64])] = None
    available_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    calibrated_at: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34Z"])
    ] = None
    basis_gates: Annotated[
        list[str] | None,
        Field(
            examples=[
                [
                    "x",
                    "y",
                    "z",
                    "h",
                    "s",
                    "sdg",
                    "t",
                    "tdg",
                    "rx",
                    "ry",
                    "rz",
                    "cx",
                    "cz",
                    "swap",
                    "u1",
                    "u2",
                    "u3",
                    "u",
                    "p",
                    "id",
                    "sx",
                    "sxdg",
                ]
            ]
        ),
    ] = None
    supported_instructions: Annotated[
        list[str] | None, Field(examples=[["measure", "barrier", "reset"]])
    ] = None
    description: Annotated[
        str | None, Field(examples=["Superconducting quantum computer"])
    ] = None


class DeviceInfoHistoryEntry(BaseModel):
    history_id: Annotated[str, Field(examples=["018f4c8a-7c2b-7f4d-9a2f-4f2f0b8f6f12"])]
    """
    Unique string identifying the device history.
    """
    device_id: Annotated[str, Field(examples=["qulacs"])]
    calibrated_at: Annotated[AwareDatetime, Field(examples=["2024-03-04T12:34:56Z"])]
    n_qubits: Annotated[int, Field(examples=[64])]
    n_couplings: Annotated[int, Field(examples=[72])]


class DeviceInfoHistoryListResponse(BaseModel):
    items: list[DeviceInfoHistoryEntry]
    total: Annotated[int, Field(examples=[3])]
    limit: Annotated[int, Field(examples=[100])]
    offset: Annotated[int, Field(examples=[0])]


class DeviceInfoHistoryDetail(DeviceInfoHistoryEntry):
    device_info: Annotated[
        str,
        Field(
            examples=[
                "https://oqtopus-cloud.s3.amazonaws.com/device_histories/018f4c8a-7c2b-7f4d-9a2f-4f2f0b8f6f12/device_info.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE"
            ]
        ),
    ]
    """
    Presigned URL for downloading the historical device_info.zip.
    """


class DeviceInfoUploadPresignedURL(BaseModel):
    """
    Presigned URL for uploading device_info.zip to OQTOPUS cloud.
    """

    url: Annotated[str, Field(examples=["https://oqtopus-cloud.s3.amazonaws.com/"])]
    fields: dict[str, Any]


class DeviceInfoUploadResponse(BaseModel):
    presigned_url: DeviceInfoUploadPresignedURL
