# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel


class InternalServerError(BaseModel):
    message: str


class NotFoundError(BaseModel):
    message: str


class BadRequestError(BaseModel):
    message: str
