# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel


class InternalServerError(BaseModel):
    detail: str


class NotFoundError(BaseModel):
    detail: str
