# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class BadRequestError(BaseModel):
    message: Annotated[
        str, Field(examples=["Invalid parameter in request body: parameter_name."])
    ]
    message_code: Annotated[str, Field(examples=["INVALID_PARAMETER"])]
    message_params: Annotated[
        dict[str, Any], Field(examples=[{"parameter": "parameter_name"}])
    ] = {}


class InternalServerError(BaseModel):
    message: Annotated[str, Field(examples=["Internal Server Error"])] = (
        "Internal Server Error"
    )
    message_code: Annotated[str, Field(examples=["INTERNAL_SERVER_ERROR"])] = (
        "INTERNAL_SERVER_ERROR"
    )
    message_params: Annotated[dict[str, Any], Field(examples=[{}])] = {}


class NotFoundError(BaseModel):
    message: Annotated[str, Field(examples=["Resource id=1 not found."])]
    message_code: Annotated[str, Field(examples=["RESOURCE_NOT_FOUND"])]
    message_params: Annotated[dict[str, Any], Field(examples=[{"id": "1"}])] = {}
