# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class GetNewsResponse(BaseModel):
    id: Annotated[int, Field(examples=[0])]
    title: Annotated[str, Field(examples=["Example Title"])]
    content: Annotated[str, Field(examples=["Example Content"])]
    start_time: Annotated[AwareDatetime, Field(examples=["2022-10-19T11:45:34+09:00"])]
    end_time: Annotated[AwareDatetime, Field(examples=["2022-12-19T11:45:34+09:00"])]
    publishable: Annotated[bool, Field(examples=[True])]


class GetNewsListResponse(BaseModel):
    news: list[GetNewsResponse] | None = None


class RegisterNewsRequest(BaseModel):
    """
    register news to backend
    """

    title: str
    content: str
    start_time: AwareDatetime
    end_time: AwareDatetime
    publishable: bool


class UpdateNewsRequest(BaseModel):
    """
    register news to backend
    """

    title: str | None = None
    content: str | None = None
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None
    publishable: bool | None = None
