# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class SuccessResponse(BaseModel):
    message: Annotated[str, Field(examples=["Operation completed successfully."])]
    message_code: Annotated[str, Field(examples=["OPERATION_SUCCESSFUL"])]
    message_params: Annotated[dict[str, Any], Field(examples=[{}])] = {}
