# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel


class UserStatus(str, Enum):
    approved = "approved"
    unapproved = "unapproved"
    suspended = "suspended"


class GetOneUserResponse(BaseModel):
    """
    detail of users response
    """

    id: int
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    status: UserStatus | None = None
    group_id: str | None = None
    available_devices: list[str] | Literal["*"] | None = None


class GetUsersResponse(BaseModel):
    offset: str | None = None
    limit: str | None = None
    users: list[GetOneUserResponse] | None = None


class UpdateUserRequest(BaseModel):
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    status: UserStatus | None = None
    group_id: str | None = None
    available_devices: list[str] | Literal["*"] | None = None
