# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel

from . import user


class GetUsersResponse(BaseModel):
    Offset: str | None = None
    Limit: str | None = None
    users: list[user.GetOneUserResponse] | None = None
