# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel


class GetOneUserResponse(BaseModel):
    """
    detail of users response
    """

    id: int
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    status: str | None = None
    group_id: str | None = None
    require_mfa_reset: bool | None = None


class GetUsersResponse(BaseModel):
    offset: str | None = None
    limit: str | None = None
    users: list[GetOneUserResponse] | None = None


class UpdateUserStatusRequest(BaseModel):
    status: str | None = None
