# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class GetOneUserResponse(BaseModel):
    """
    detail of users response
    """

    id: int
    email: str | None = None
    name: str | None = None
    organization: str | None = None
    status: int | None = None
    group_id: str | None = None
    require_mfa_reset: bool | None = None


class Status(str, Enum):
    """
    status 1: active, 3: inactive
    """

    field_1 = "1"
    field_3 = "3"


class UserUpdateStatusRequest(BaseModel):
    status: Status | None = None
    """
    status 1: active, 3: inactive
    """
