# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from pydantic import BaseModel

from . import whitelist_user


class GetWhitelistUsersResponse(BaseModel):
    users: list[whitelist_user.GetWhitelistUserResponse] | None = None


class WhitelistUsersRegisterRequest(BaseModel):
    users: list[whitelist_user.WhitelistUserRegisterRequest] | None = None


class WhitelistUsersDeleteRequest(BaseModel):
    user_emails: list[str] | None = None
