# generated by datamodel-codegen
# ruff: noqa


from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class GetWhitelistUserResponse(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    group_id: Annotated[str, Field(examples=["group1"])]
    email: Annotated[str, Field(examples=["example@example.com"])]
    username: Annotated[str | None, Field(examples=["exampleuser"])] = None
    organization: Annotated[str | None, Field(examples=["Example Organization"])] = None
    is_signup_completed: Annotated[bool | None, Field(examples=[True])] = None


class WhitelistUserRegisterRequest(BaseModel):
    """
    Whitelist user register request
    """

    group_id: str | None = None
    email: str | None = None
    username: str | None = None
    organization: str | None = None
