__all__ = ("AbstractFileSystem", "filesystem")

from typing import Any, BinaryIO, Iterator, Tuple

def filesystem(protocol: str, **kwargs: Any) -> AbstractFileSystem: ...

class AbstractFileSystem:
    def _strip_protocol(self, path: Any) -> list | str: ...
    def open(self, path: str, mode: str = "rb") -> BinaryIO: ...
    def makedirs(self, path: Any, exist_ok: bool = False) -> None: ...
    def rm(
        self, path: Any, recursive: bool = False, maxdepth: Any | None = None
    ) -> None: ...
    def mkdir(
        self, path: str, create_parents: bool = True, exist_ok: bool = True
    ) -> None: ...
    def info(self, path: str, **kwargs: Any) -> dict[str, Any]: ...
    def exists(self, path: str) -> bool: ...
    def isfile(self, path: str) -> bool: ...
    def isdir(self, path: str) -> bool: ...
    def walk(self, path: str) -> Iterator[Tuple[str, list[str], list[str]]]: ...
