name: deployment
on:
  push:
    branches:
    - develop

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oqtopus-oqtopus-dev-deploy-lambda

      - name: Set AWS Profile
        run: |
          ACCOUNT_NAME=$(aws iam list-account-aliases --query "AccountAliases[0]" --output text)
          echo "PROFILE=$ACCOUNT_NAME" >> $GITHUB_ENV


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Install Poetry
        run: |
          pip install poetry poetry-plugin-export
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install poetry dependencies
        run: poetry install

      - name: Install make
        run: sudo apt install make

      - name: Deploy
        working-directory: ./deployment/oqtopus-dev
        run: sudo -E env PATH="$PATH" make deploy-all