name: deployment
on:
  push:
    branches:
    - develop

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install make

      - name: Deploy
        working-directory: ./deployment
        run: make deploy-all