name: deployment
on:
  push:
    branches:
    - develop

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oqtopus-oqtopus-dev-deploy-lambda

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install poetry dependencies
        run: poetry install

      - name: Install make
        run: sudo apt install make

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: ./deployment/oqtopus-dev
        run: make deploy-all