name: Detect OpenAPI breaking changes

on:
  push:
    branches:
      - 'test/#335-auto-detect-oas-breaking-changes'
    paths:
      - '.github/workflows/**'
      - 'backend/oas/**'
      # - 'backend/oas/admin/**'
      # - 'backend/oas/provider/**'
      # - 'backend/oas/user/**'
      # - 'backend/oas/user_signup/**'
jobs:
  detect-openapi-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      # - name: HelloWorld
      #   run: |
      #     echo "Branch: ${{ github.ref_name }}"
      #     echo "Commit: ${{ github.sha }}"

      - name: Fetch base OpenAPI spec
        run: |
          # Make sure we have the latest base ref
          git fetch origin develop

          # Extract the OpenAPI spec from base into a temp file
          git show origin/develop:backend/oas/user/openapi.yaml > openapi_base.yaml

      - name: Run oasdiff
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: openapi_base.yaml
          revision: backend/oas/user/openapi.yaml
          fail-on: WARN
