name: OpenAPI Check

on:
  push:
    branches:
      - 'test/#335-auto-detect-oas-breaking-changes'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HelloWorld
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
