name: OpenAPI Check

on:
  push:
    branches:
      - 'test/#335-auto-detect-oas-breaking-changes'
    paths:
      - '.github/workflows/**'
      - 'backend/oas/**'
      # - 'backend/oas/admin/**'
      # - 'backend/oas/provider/**'
      # - 'backend/oas/user/**'
      # - 'backend/oas/user_signup/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HelloWorld
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
