name: Python CI

on:
  push:
    paths:
      - 'backend/**/*.py'

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [common, user, provider]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install poetry
          poetry install
      - name: Check version
        run: |
          poetry --version
      - name: Lint and Format ${{ matrix.target }}
        run: |
          make lint-${{ matrix.target }}
          make fmt-${{ matrix.target }}
        working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    needs: lint-format
    strategy:
      matrix:
        target: [common, user, provider]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install poetry
          poetry install
      - name: Check version
        run: |
          poetry --version
      - name: Test ${{ matrix.target }}
        run: |
          make test-${{ matrix.target }}
        working-directory: ./backend
        env:
          TZ: Asia/Tokyo
