name: Slack Test Workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  send-message:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: ['z_yugo_github_test']
    steps:
      - name: Dummy deploy
        run: |
          my_invalid_command 2> error.log

      - name: On Success
        if: ${{ success() }}
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST https://slack.com/api/chat.postMessage \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $SLACK_API_TOKEN" \
          --data @- <<EOF
          {
            "channel": "${{ matrix.channel }}",
            "text": "✅ Deploy successful",
            "attachments": [
              {
                "color": "#00dd00",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Log*"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "[${TIMESTAMP}] Deployed successfully!"
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Action*"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${RUN_URL}"
                    }
                  },
                  {
                    "type": "divider"
                  }
                ]
              }
            ]
          }
          EOF

      - name: On Failure
        if: ${{ failure() }}
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE=$(cat error.log)
          curl -X POST https://slack.com/api/chat.postMessage \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $SLACK_API_TOKEN" \
          --data @- <<EOF
          {
            "channel": "${{ matrix.channel }}",
            "text": "❌ Deploy failed",
            "attachments": [
              {
                "color": "#dd0000",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Log*"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "[${TIMESTAMP}] ${MESSAGE}"
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Action*"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${RUN_URL}"
                    }
                  },
                  {
                    "type": "divider"
                  }
                ]
              }
            ]
          }
          EOF
